FROM alpine

RUN apk add --no-cache php7 php7-fpm php7-opcache php7-pdo php7-pdo_mysql \
 php7-zip php7-xml php7-intl php7-openssl php7-gd php7-gmp  php7-curl php7-mbstring \
 php7-pcntl php7-phar php7-pdo_sqlite php7-sodium